/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Negocio.PuenteLista;
import Negocio.PuenteObservaciones;
import Negocio.PuenteRegistro;
import datos.DLista;
import datos.DObservaciones;
import datos.DRegistro;
import javax.swing.JOptionPane;

/**
 *
 * @author JESUS
 */
public class PrincipalJefe extends javax.swing.JFrame {
Revisión gru=new Revisión();

     
    public PrincipalJefe() {
        initComponents();
        MostrarTabla();
        MostrarTabla1();
        txtIDM.setEnabled(false);
       M();
       txtNOU.setEnabled(false);
       idm.setEnabled(false);
       idmn.setEnabled(false);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        clb = new javax.swing.JTextField();
        u = new javax.swing.JTextField();
        o = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idmn = new javax.swing.JTextField();
        idm = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNOU = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblm = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        xxx = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtO = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        txtIDM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaO = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDatosx = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 20, 210));

        jLabel4.setText("Nombre de la Asignatura");

        jLabel9.setText("Clave");

        jLabel10.setText("Horas teoria");

        jLabel11.setText("Horas practica");

        jLabel12.setText("Unidades");

        jLabel13.setText("Grupo");

        r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rKeyTyped(evt);
            }
        });

        clb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clbKeyTyped(evt);
            }
        });

        u.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uKeyTyped(evt);
            }
        });

        i.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iKeyTyped(evt);
            }
        });

        jLabel14.setText("Id Maestro");

        jLabel15.setText("Nombre Maestro");

        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });
        y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(clb, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(idm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15))))
                            .addComponent(jLabel14))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idmn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(46, 46, 46))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(clb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(idmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 380, 190));

        jButton6.setText("Nuevo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 30, -1, -1));

        jButton7.setText("Agregar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 70, -1, -1));

        jButton8.setText("Modificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 120, -1, -1));

        jButton9.setText("Eliminar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 160, -1, -1));

        jLabel7.setText("DOCENTE");

        jLabel8.setText("Nombre");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Revisar Registros");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(55, 55, 55)
                        .addComponent(txtNOU, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNOU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        tblm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblm);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 140));

        jLabel3.setText("Tabla Docente");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Area Jefe");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 30));

        jButton1.setText("jButton1");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jButton11.setText("Refrescar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 230));

        jLabel6.setText("Escribir observacion");

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        xxx.setText("Enivar");
        xxx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xxxActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        jLabel1.setText("Id");

        jButton10.setText("Nuevo");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        txtIDM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDMKeyTyped(evt);
            }
        });

        jLabel2.setText("Id Maestro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtIDM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton10)
                                .addGap(40, 40, 40)))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtO, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(xxx)
                                .addGap(72, 72, 72)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtIDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtO, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xxx)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 500, 210));

        TablaO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaOMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaO);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 490, 180));

        TablaDatosx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDatosx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosxMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaDatosx);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 610, 400));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void Limpiar2(){
        r.setText("");
        clb.setText("");
        y.setText("");
        u.setText("");
        i.setText("");
        i.setText("");
        o.setText("");
        idm.setText("");
        idmn.setText("");
       
        
    }
    void limpiaro(){
        txtId.setText("");
        txtIDM.setText("");
        txtO.setText("");
    }
    void MostrarTabla1(){
        new Negocio.PuenteObservaciones().PuenteMostrarTabla(TablaO);
    }
    void M(){
        new Negocio.PuenteMaestros().PuenteMostrarTabla(tblm);
    }
     
   public boolean Verificar1(){
        boolean v;
        if(txtId.getText().isEmpty()||txtO.getText().isEmpty()||txtIDM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"llenar todos los datos","falta de datos",JOptionPane.INFORMATION_MESSAGE);
            v=false;
        }else
            v=true;
        return v;
    }
   public boolean VerificarNOU(){
        boolean v;
        if(txtNOU.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"llenar todos los datos","falta de datos",JOptionPane.INFORMATION_MESSAGE);
            v=false;
        }else
            v=true;
        return v;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(Verificar1()){
                DObservaciones prod=new DObservaciones();
                
                 prod.setId(Integer.parseInt(txtId.getText()));
                 prod.setId_Maestro(Integer.parseInt(txtIDM.getText()));
                 prod.setObservacion(txtO.getText());
               
                 

                
               

                 new PuenteObservaciones().PuenteActualizar(prod);
                        limpiaro();
                MostrarTabla1();
            } // add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(VerificarNOU()){
      gru.setVisible(true);
}
else{
                JOptionPane.showMessageDialog(null,"Elije a un maestro de la tabla maestros");
            }
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void xxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xxxActionPerformed
 if(Verificar1()){   
        DObservaciones prod=new DObservaciones();
                prod.setId(Integer.parseInt(txtId.getText()));
                prod.setId_Maestro(Integer.parseInt(txtIDM.getText()));
                prod.setObservacion(txtO.getText());
                
                
                  
//prod.setPromedio(Float.parseFloat(txtp.getText()));
                new PuenteObservaciones().PuenteRegistro(prod);
                        limpiaro();
                MostrarTabla1();}
        else{
                JOptionPane.showMessageDialog(null,"Debes llenar todos los campos");
            }         // TODO add your handling code here:
    }//GEN-LAST:event_xxxActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton7.setEnabled(true);
        Limpiar2();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    public boolean Verificar(){
        boolean v;
        if(clb.getText().isEmpty()||r.getText().isEmpty()||y.getText().isEmpty()||
                u.getText().isEmpty()||i.getText().isEmpty()||o.getText().isEmpty()||idm.getText().isEmpty()||idmn.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"llenar todos los datos","falta de datos",JOptionPane.INFORMATION_MESSAGE);
            v=false;
        }else
            v=true;
        return v;
    }
    void MostrarTabla(){
        new Negocio.PuenteRegistro().PuenteMostrarTabla(TablaDatosx);
        
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 if(Verificar()){   
        DRegistro prod=new DRegistro();
                prod.setClave(Integer.parseInt(clb.getText()));
                prod.setNombre_de_la_asignatura(r.getText());
                
                 prod.setHorasTeoria(Integer.parseInt(y.getText()));
                 prod.setHorasPractica(Integer.parseInt(u.getText()));
                 prod.setUnidades(Integer.parseInt(i.getText()));
                 prod.setGrupo(o.getText());
                  prod.setId_Maestro(Integer.parseInt(idm.getText()));
                 prod.setNombre_Maestro(idmn.getText());
                  
//prod.setPromedio(Float.parseFloat(txtp.getText()));
                new PuenteRegistro().PuenteRegistro(prod);
                        Limpiar2();
                MostrarTabla();}
        else{
                JOptionPane.showMessageDialog(null,"Debes llenar todos los campos");
            }        // TODO add your handling code here:
            
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
if(Verificar()){

                DRegistro prod=new DRegistro();
                 prod.setClave(Integer.parseInt(clb.getText()));
                 prod.setNombre_de_la_asignatura(r.getText());
               
                 prod.setHorasTeoria(Integer.parseInt(y.getText()));
                 prod.setHorasPractica(Integer.parseInt(u.getText()));
                 prod.setUnidades(Integer.parseInt(i.getText()));
                 prod.setGrupo(o.getText());
                prod.setId_Maestro(Integer.parseInt(idm.getText()));
                 prod.setNombre_Maestro(idmn.getText());

                
               

                 new PuenteRegistro().PuenteActualizar(prod);
                Limpiar2();
                MostrarTabla();
            }         // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
if(Verificar()){
                int n=JOptionPane.showConfirmDialog(null,"¿realmente deseas eliminar este registro?");
                if(n==0){
                    DRegistro pro=new DRegistro();
                    pro.setClave(Integer.parseInt(clb.getText()));
                    new PuenteRegistro().PuenteEliminar(pro);
                    Limpiar2();
                    MostrarTabla();
                }
            }else{
                JOptionPane.showMessageDialog(null,"Deben estar llenos todos los campos");
            }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void TablaDatosxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosxMouseClicked
        Limpiar2();
        jButton7.setEnabled(false);
      
        if(evt.getButton()==1){
            Limpiar2();
            jButton7.setEnabled(false);
            int fila=TablaDatosx.getSelectedRow();

            //****para pasar a formato de JDataChosser (la fecha)*********
           // String fe=TablaDatos.getValueAt(fila, 5).toString();
            //DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
            
            //*************************************************
            clb.setText(TablaDatosx.getValueAt(fila, 0).toString());
            r.setText(TablaDatosx.getValueAt(fila, 1).toString());
           
         
            
            u.setText(TablaDatosx.getValueAt(fila, 2).toString());
             y.setText(TablaDatosx.getValueAt(fila, 3).toString());
              i.setText(TablaDatosx.getValueAt(fila, 4).toString());
             
            o.setText(TablaDatosx.getValueAt(fila, 5).toString());
            idm.setText(TablaDatosx.getValueAt(fila, 6).toString());
            idmn.setText(TablaDatosx.getValueAt(fila, 7).toString());
           
            
    }          
    }//GEN-LAST:event_TablaDatosxMouseClicked

    private void rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rKeyTyped
char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_rKeyTyped

    private void clbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clbKeyTyped
char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();          // TODO add your handling code here:
    }//GEN-LAST:event_clbKeyTyped

    private void yKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yKeyTyped
char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();          // TODO add your handling code here:
    }//GEN-LAST:event_yKeyTyped

    private void uKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uKeyTyped
char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();          // TODO add your handling code here:
    }//GEN-LAST:event_uKeyTyped

    private void iKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iKeyTyped
char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();          // TODO add your handling code here:
    }//GEN-LAST:event_iKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(Verificar1()){
                int n=JOptionPane.showConfirmDialog(null,"¿realmente deseas eliminar este registro?");
                if(n==0){
                    DObservaciones pro=new DObservaciones();
                    pro.setId(Integer.parseInt(txtId.getText()));
                    new PuenteObservaciones().PuenteEliminar(pro);
                    limpiaro();
                    MostrarTabla1();
                }
            }else{
                JOptionPane.showMessageDialog(null,"Deben estar llenos todos los campos");
            }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TablaOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaOMouseClicked
limpiaro();
    xxx.setEnabled(false);
      
        if(evt.getButton()==1){
            limpiaro();
           xxx.setEnabled(false);
            int fila=TablaO.getSelectedRow();

            //****para pasar a formato de JDataChosser (la fecha)*********
           // String fe=TablaDatos.getValueAt(fila, 5).toString();
            //DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
            
            //*************************************************
            txtId.setText(TablaO.getValueAt(fila, 0).toString());
            txtIDM.setText(TablaO.getValueAt(fila, 1).toString());
            txtO.setText(TablaO.getValueAt(fila, 2).toString());
           
         
            
            
        }               // TODO add your handling code here:
    }//GEN-LAST:event_TablaOMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         xxx.setEnabled(true);
        limpiaro();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tblmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmMouseClicked
 //Limpiar2();
      //  jButton7.setEnabled(false);
      
        if(evt.getButton()==1){
            //Limpiar2();
            //jButton7.setEnabled(false);
            int fila=tblm.getSelectedRow();

            //****para pasar a formato de JDataChosser (la fecha)*********
           // String fe=TablaDatos.getValueAt(fila, 5).toString();
            //DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
            
            //*************************************************
            txtNOU.setText(tblm.getValueAt(fila, 1).toString());
            txtIDM.setText(tblm.getValueAt(fila, 0).toString());
           idm.setText(tblm.getValueAt(fila, 0).toString());
            idmn.setText(tblm.getValueAt(fila, 1).toString());
           
         
           
           
           
            
    }                  // TODO add your handling code here:
    }//GEN-LAST:event_tblmMouseClicked

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtIDMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDMKeyTyped
char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMKeyTyped

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
MostrarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJefe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatosx;
    private javax.swing.JTable TablaO;
    private javax.swing.JTextField clb;
    private javax.swing.JTextField i;
    private javax.swing.JTextField idm;
    private javax.swing.JTextField idmn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField o;
    private javax.swing.JTextField r;
    private javax.swing.JTable tblm;
    private javax.swing.JTextField txtIDM;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNOU;
    private javax.swing.JTextField txtO;
    private javax.swing.JTextField u;
    private javax.swing.JButton xxx;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
