/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Negocio.PuenteCalifas;
import Negocio.PuenteEvaluacion;
import Negocio.PuenteLista;
import datos.DCalificaciones;
import datos.DLista;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Saenz
 */
public class Revisión extends javax.swing.JFrame {

    /**
     * Creates new form Revisión
     */
    public Revisión() {
        initComponents();
         MostrarTabla();
         MostrarTabla2();
         MostrarTabla3();
         MostrarTabla4();
         MostrarTablax1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPestañas = new javax.swing.JTabbedPane();
        txtNombre = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos3 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtnc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        mnmc = new javax.swing.JTextField();
        txtn = new javax.swing.JTextField();
        txtx = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        buscar1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        pResumen = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        oloc = new javax.swing.JTextField();
        olonc = new javax.swing.JTextField();
        olon = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        pEscolares = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        w = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        cate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        clb = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        u = new javax.swing.JTextField();
        o = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        p = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        l = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        k = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaDatos4 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TablaDatosx1 = new javax.swing.JTable();
        jButton25 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaDatos2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtu = new javax.swing.JTextField();
        txtcr = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txta = new javax.swing.JTextField();
        txtev = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txte = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        mz = new javax.swing.JTextField();
        idx = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        lbMostrarImagen = new javax.swing.JLabel();
        lbMostrarImagen2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPestañas.setBackground(new java.awt.Color(102, 102, 255));

        txtNombre.setBackground(new java.awt.Color(102, 102, 255));
        txtNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDatos3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"2", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"5", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"9", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"10", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"11", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"12", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"13", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"14", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"15", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"16", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"17", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"18", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"19", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"20", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"21", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"22", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"23", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"24", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"25", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"26", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"27", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NC", " NOMBRE", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
            }
        ));
        TablaDatos3.setColumnSelectionAllowed(true);
        TablaDatos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatos3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaDatos3);

        txtNombre.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 760, 460));

        jButton6.setText("salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        txtNombre.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 120, 50));

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));

        jLabel14.setText("Nombre");

        jLabel15.setText("Numero de control");

        txtnc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtncKeyTyped(evt);
            }
        });

        jLabel18.setText("Carrera");

        jLabel32.setText("Clalve materia");

        mnmc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnmcKeyTyped(evt);
            }
        });

        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnKeyTyped(evt);
            }
        });

        txtx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas", "IGE", "Industrial", "Electromecanica", "Renovables" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mnmc, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtn)
                            .addComponent(txtx, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(txtnc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(146, 146, 146))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mnmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        txtNombre.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 490, 210));

        jPanel9.setBackground(new java.awt.Color(102, 204, 255));

        jButton19.setText("Electromecanica");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Sistemas");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("Todos");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("Renovables");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("Industrial");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("IGE");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton19)
                .addGap(35, 35, 35)
                .addComponent(jButton24)
                .addGap(26, 26, 26)
                .addComponent(jButton23)
                .addGap(33, 33, 33)
                .addComponent(jButton22)
                .addGap(35, 35, 35)
                .addComponent(jButton20)
                .addGap(51, 51, 51))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20)
                    .addComponent(jButton22)
                    .addComponent(jButton23)
                    .addComponent(jButton24)
                    .addComponent(jButton19)
                    .addComponent(jButton21))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        txtNombre.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 720, -1));

        jButton29.setText("Buscar");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        txtNombre.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, -1, -1));
        txtNombre.add(buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 140, -1));

        jLabel36.setText("Buscar por numero de control");
        txtNombre.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, -1, -1));

        PanelPestañas.addTab("Lista", txtNombre);

        pResumen.setBackground(new java.awt.Color(153, 255, 102));
        pResumen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaDatos);

        pResumen.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 820, 460));

        jButton5.setText("salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pResumen.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 120, 50));

        jLabel8.setText("Unidad 6");
        pResumen.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        txt6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt6KeyTyped(evt);
            }
        });
        pResumen.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 40, -1));

        jLabel16.setText("Clave materia");
        pResumen.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel25.setText("Unidad 2");
        pResumen.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel26.setText("Unidad 3");
        pResumen.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel27.setText("Unidad 4");
        pResumen.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel28.setText("Unidad 5");
        pResumen.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });
        pResumen.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 40, -1));

        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt3KeyTyped(evt);
            }
        });
        pResumen.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 40, -1));

        txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt4KeyTyped(evt);
            }
        });
        pResumen.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 40, -1));

        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt5KeyTyped(evt);
            }
        });
        pResumen.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 40, -1));

        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });
        pResumen.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 40, -1));

        jLabel17.setText("Unidad 1");
        pResumen.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        oloc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                olocKeyTyped(evt);
            }
        });
        pResumen.add(oloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 240, -1));
        pResumen.add(olonc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 240, -1));

        olon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                olonKeyTyped(evt);
            }
        });
        pResumen.add(olon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, -1));

        jLabel30.setText("Numero de Control");
        pResumen.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel31.setText("Nombre");
        pResumen.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel21.setText("Carrera");
        pResumen.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclaveKeyTyped(evt);
            }
        });
        pResumen.add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 240, -1));

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));

        jButton18.setText("Electromecanica");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton10.setText("Sistemas");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton13.setText("Todos");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton17.setText("Renovables");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton16.setText("Industrial");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton15.setText("IGE");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton18)
                .addGap(35, 35, 35)
                .addComponent(jButton15)
                .addGap(26, 26, 26)
                .addComponent(jButton16)
                .addGap(33, 33, 33)
                .addComponent(jButton17)
                .addGap(35, 35, 35)
                .addComponent(jButton10)
                .addGap(51, 51, 51))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton17)
                    .addComponent(jButton16)
                    .addComponent(jButton15)
                    .addComponent(jButton18)
                    .addComponent(jButton13))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pResumen.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 720, -1));

        jButton27.setText("Buscar");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        pResumen.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 550, -1, -1));
        pResumen.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 140, -1));

        jLabel35.setText("Buscar por numero de control");
        pResumen.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, -1, -1));

        PanelPestañas.addTab("Calificaciones", pResumen);

        pEscolares.setBackground(new java.awt.Color(204, 255, 204));
        pEscolares.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Catedratico");

        jLabel2.setText("Plan de estudios");

        jLabel3.setText("Periodo");

        w.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wKeyTyped(evt);
            }
        });

        cate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cateKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pEscolares.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 180));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel4.setText("Nombre de la Asignatura");

        jLabel9.setText("Clave");

        jLabel10.setText("Horas teoria");

        jLabel11.setText("Horas practica");

        jLabel12.setText("Unidades");

        jLabel13.setText("Grupo");

        r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rKeyTyped(evt);
            }
        });

        clb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clbKeyTyped(evt);
            }
        });

        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });
        y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yKeyTyped(evt);
            }
        });

        u.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uKeyTyped(evt);
            }
        });

        i.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(clb, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(39, 39, 39)
                                .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(y)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(u)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(clb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pEscolares.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 400, 160));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Caracterización de la asignatura");

        p.setColumns(20);
        p.setRows(5);
        p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(p);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Competencia");

        l.setColumns(20);
        l.setRows(5);
        l.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(l);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Intencion didactica");

        k.setColumns(20);
        k.setRows(5);
        k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(k);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pEscolares.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 720, 400));

        jButton7.setText("salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pEscolares.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 180, 70, -1));

        TablaDatos4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDatos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatos4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(TablaDatos4);

        pEscolares.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 860, 230));

        jPanel10.setBackground(new java.awt.Color(51, 102, 255));

        TablaDatosx1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDatosx1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosx1MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(TablaDatosx1);

        jButton25.setText("Refresh");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButton25)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton25)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pEscolares.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 390, 210));

        PanelPestañas.addTab("Planeacion", pEscolares);

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 232, -1, -1));

        TablaDatos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        TablaDatos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatos2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TablaDatos2);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 540, 330));

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("Unidad");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuKeyTyped(evt);
            }
        });
        jPanel6.add(txtu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 30, -1));

        txtcr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcrKeyTyped(evt);
            }
        });
        jPanel6.add(txtcr, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 250, 150));

        jLabel22.setText("Actividades para el logro de las tareas de desempeño");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        txta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaKeyTyped(evt);
            }
        });
        jPanel6.add(txta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 260, 80));

        txtev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtevKeyTyped(evt);
            }
        });
        jPanel6.add(txtev, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 260, 80));

        jLabel23.setText("Evidecias");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel24.setText("Criteriios de evaluacion");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        txte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txteKeyTyped(evt);
            }
        });
        jPanel6.add(txte, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 30, -1));

        jLabel29.setText("Etapa");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel33.setText("Materia");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel6.add(mz, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 60, -1));
        jPanel6.add(idx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, -1));

        jLabel34.setText("Id");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1130, 250));

        lbMostrarImagen.setBackground(new java.awt.Color(255, 255, 255));
        lbMostrarImagen.setOpaque(true);
        jPanel5.add(lbMostrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 330, 280));

        lbMostrarImagen2.setBackground(new java.awt.Color(255, 255, 255));
        lbMostrarImagen2.setOpaque(true);
        jPanel5.add(lbMostrarImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 330, 270));

        PanelPestañas.addTab("Evaluacion", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1305, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaDatos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatos3MouseClicked
       // Limpiar3();
        //asc.setEnabled(false);

        if(evt.getButton()==1){
          //  Limpiar3();
           // asc.setEnabled(false);
            int fila=TablaDatos3.getSelectedRow();

            //****para pasar a formato de JDataChosser (la fecha)*********
            // String fe=TablaDatos.getValueAt(fila, 5).toString();
            //DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");

            //*************************************************
            txtnc.setText(TablaDatos3.getValueAt(fila, 0).toString());
            olonc.setText(TablaDatos3.getValueAt(fila, 0).toString());

            mnmc.setText(TablaDatos3.getValueAt(fila, 1).toString());
            txtclave.setText(TablaDatos3.getValueAt(fila, 1).toString());
            txtn.setText(TablaDatos3.getValueAt(fila, 2).toString());
            olon.setText(TablaDatos3.getValueAt(fila, 2).toString());

            txtx.setSelectedItem(TablaDatos3.getValueAt(fila, 3).toString());
            oloc.setText(TablaDatos3.getValueAt(fila, 3).toString());

        }                 // TODO add your handling code here:
    }//GEN-LAST:event_TablaDatos3MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtncKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtncKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();          // TODO add your handling code here:
    }//GEN-LAST:event_txtncKeyTyped

    private void mnmcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnmcKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_mnmcKeyTyped

    private void txtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_txtnKeyTyped

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        new Negocio.PuenteLista().PuenteMostrarTablaElectromecanica(TablaDatos3);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        new Negocio.PuenteLista().PuenteMostrarTablaSistemas(TablaDatos3);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        new Negocio.PuenteLista().PuenteMostrarTabla3(TablaDatos3);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        new Negocio.PuenteLista().PuenteMostrarTablaRenovables(TablaDatos3);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        new Negocio.PuenteLista().PuenteMostrarTablaIndustrial(TablaDatos3);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        new Negocio.PuenteLista().PuenteMostrarTablaIGE(TablaDatos3);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        if(!buscar1.getText().isEmpty()){
            DLista prov=new DLista();
            prov.setNC(Integer.parseInt(buscar1.getText()));
            new PuenteLista().PuenteBuscar(prov);
            txtnc.setText(""+prov.getNC());
            mnmc.setText(""+prov.getClaveMateria());
            txtn.setText(prov.getNombre());
            txtx.setSelectedItem(""+prov.getCarrera());

        }
        else{
            JOptionPane.showMessageDialog(null, "Debes introducir un Numero de control","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        Limpiar();
//        btnagregar.setEnabled(false);

        if(evt.getButton()==1){
            Limpiar();
            olonc.setEnabled(false);
            int fila=TablaDatos.getSelectedRow();

            //****para pasar a formato de JDataChosser (la fecha)*********
            // String fe=TablaDatos.getValueAt(fila, 5).toString();
            //DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");

            //*************************************************
            olonc.setText(TablaDatos.getValueAt(fila, 0).toString());

            olon.setText(TablaDatos.getValueAt(fila, 1).toString());
            oloc.setText(TablaDatos.getValueAt(fila, 2).toString());
            txtclave.setText(TablaDatos.getValueAt(fila, 3).toString());
            txt1.setText(TablaDatos.getValueAt(fila, 4).toString());
            txt2.setText(TablaDatos.getValueAt(fila, 5).toString());
            txt3.setText(TablaDatos.getValueAt(fila, 6).toString());
            txt4.setText(TablaDatos.getValueAt(fila, 7).toString());
            txt5.setText(TablaDatos.getValueAt(fila, 8).toString());

            txt6.setText(TablaDatos.getValueAt(fila, 9).toString());

        }

    }//GEN-LAST:event_TablaDatosMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt6KeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txt6KeyTyped

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txt2KeyTyped

    private void txt3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txt3KeyTyped

    private void txt4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txt4KeyTyped

    private void txt5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txt5KeyTyped

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txt1KeyTyped

    private void olocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_olocKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_olocKeyTyped

    private void olonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_olonKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_olonKeyTyped

    private void txtclaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclaveKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveKeyTyped

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        new Negocio.PuenteCalifas().PuenteMostrarTablaElectromecanica(TablaDatos);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new Negocio.PuenteCalifas().PuenteMostrarTablaSistemas(TablaDatos);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        new Negocio.PuenteCalifas().PuenteMostrarTabla(TablaDatos);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new Negocio.PuenteCalifas().PuenteMostrarTablaRenovables(TablaDatos);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        new Negocio.PuenteCalifas().PuenteMostrarTablaIndustrial(TablaDatos);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        new Negocio.PuenteCalifas().PuenteMostrarTablaIGE(TablaDatos);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        if(!buscar.getText().isEmpty()){
            DCalificaciones prov=new DCalificaciones();
            prov.setNumero_de_Control(Integer.parseInt(buscar.getText()));
            new PuenteCalifas().PuenteBuscar(prov);
            olonc.setText(""+prov.getNumero_de_Control());
            olon.setText(prov.getNombre());
            oloc.setText(prov.getCarrera());
            txtclave.setText(""+prov.getClaveMateria());
            txt1.setText(""+prov.getU1());
            txt2.setText(""+prov.getU2());
            txt3.setText(""+prov.getU3());
            txt4.setText(""+prov.getU4());
            txt5.setText(""+prov.getU5());
            txt6.setText(""+prov.getU6());
            // txt3.setEnabled(true);
            //btnEliminar.setEnabled(true);
            //btnAgregar.setEnabled(false);
            //txtClaveP.setEditable(false);

        }
        else{
            JOptionPane.showMessageDialog(null, "Debes introducir un Numero de control","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void wKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_wKeyTyped

    private void cateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cateKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_cateKeyTyped

    private void rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_rKeyTyped

    private void clbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clbKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_clbKeyTyped

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yActionPerformed

    private void yKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_yKeyTyped

    private void uKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_uKeyTyped

    private void iKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_iKeyTyped

    private void pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_pKeyTyped

    private void lKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_lKeyTyped

    private void kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_kKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void TablaDatos4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatos4MouseClicked
        Limpiar4();
        //ac.setEnabled(false);

        if(evt.getButton()==1){
            Limpiar4();
          //  ac.setEnabled(false);
            int fila=TablaDatos4.getSelectedRow();

            //*************************************************
            clb.setText(TablaDatos4.getValueAt(fila, 0).toString());
            w.setText(TablaDatos4.getValueAt(fila, 1).toString());
            e.setText(TablaDatos4.getValueAt(fila, 2).toString());
            r.setText(TablaDatos4.getValueAt(fila, 3).toString());
            cate.setText(TablaDatos4.getValueAt(fila, 4).toString());
            y.setText(TablaDatos4.getValueAt(fila, 5).toString());
            u.setText(TablaDatos4.getValueAt(fila, 6).toString());
            i.setText(TablaDatos4.getValueAt(fila, 7).toString());
            o.setText(TablaDatos4.getValueAt(fila, 8).toString());
            p.setText(TablaDatos4.getValueAt(fila, 9).toString());
            l.setText(TablaDatos4.getValueAt(fila, 10).toString());
            k.setText(TablaDatos4.getValueAt(fila, 11).toString());

        }          // TODO add your handling code here:
    }//GEN-LAST:event_TablaDatos4MouseClicked

    private void TablaDatosx1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosx1MouseClicked

        Limpiarx1();

        if(evt.getButton()==1){
            Limpiarx1();

            int fila=TablaDatosx1.getSelectedRow();
            mnmc.setText(TablaDatosx1.getValueAt(fila, 0).toString());
            mz.setText(TablaDatosx1.getValueAt(fila, 0).toString());
            clb.setText(TablaDatosx1.getValueAt(fila, 0).toString());
            r.setText(TablaDatosx1.getValueAt(fila, 1).toString());
            y.setText(TablaDatosx1.getValueAt(fila, 2).toString());
            u.setText(TablaDatosx1.getValueAt(fila, 3).toString());
            i.setText(TablaDatosx1.getValueAt(fila, 4).toString());
            o.setText(TablaDatosx1.getValueAt(fila, 5).toString());

            cate.setText(TablaDatosx1.getValueAt(fila, 7).toString());
        }// TODO add your handling code here:
    }//GEN-LAST:event_TablaDatosx1MouseClicked

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        MostrarTablax1();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void TablaDatos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatos2MouseClicked
        Limpiar2();
        //m.setEnabled(false);

        if(evt.getButton()==1){
            Limpiar2();
          //  m.setEnabled(false);
            int fila=TablaDatos2.getSelectedRow();

            //****para pasar a formato de JDataChosser (la fecha)*********
            // String fe=TablaDatos.getValueAt(fila, 5).toString();
            //DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");

            //*************************************************
            idx.setText(TablaDatos2.getValueAt(fila, 0).toString());
            txtu.setText(TablaDatos2.getValueAt(fila, 1).toString());
            //txt.setText(TablaDatos.getValueAt(fila, 0).toString());
            //  txtNombre.setText(TablaDatos.getValueAt(fila, 1).toString());
            txte.setText(TablaDatos2.getValueAt(fila, 2).toString());
            txta.setText(TablaDatos2.getValueAt(fila, 3).toString());
            txtev.setText(TablaDatos2.getValueAt(fila, 4).toString());
            txtcr.setText(TablaDatos2.getValueAt(fila, 5).toString());
            mz.setText(TablaDatos2.getValueAt(fila, 6).toString());

            //***********codigo para obtener imagen de la BD****************
            int clv=Integer.parseInt(idx.getText());
            ImageIcon img=new PuenteEvaluacion().puenteObtenerImagen(clv);
            Icon icono=new ImageIcon(img.getImage().getScaledInstance(lbMostrarImagen.getWidth(),lbMostrarImagen.getHeight(),Image.SCALE_DEFAULT));
            if(img != null){
                lbMostrarImagen.setIcon(icono);
            }
            //**************************************************************
            //***********codigo para obtener imagen de la BD****************
            int clv2=Integer.parseInt(idx.getText());
            ImageIcon img2=new PuenteEvaluacion().puenteObtenerImagen2(clv2);
            Icon icono2=new ImageIcon(img2.getImage().getScaledInstance(lbMostrarImagen2.getWidth(),lbMostrarImagen2.getHeight(),Image.SCALE_DEFAULT));
            if(img != null){
                lbMostrarImagen2.setIcon(icono2);
            }
        }
    }//GEN-LAST:event_TablaDatos2MouseClicked

    private void txtuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuKeyTyped

        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();

    }//GEN-LAST:event_txtuKeyTyped

    private void txtcrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcrKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txtcrKeyTyped

    private void txtaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txtaKeyTyped

    private void txtevKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtevKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car>'Z')&& (car>'.'))evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txtevKeyTyped

    private void txteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txteKeyTyped
void Limpiar(){
        olonc.setText("");
        olon.setText("");
        oloc.setText("");
        txtclave.setText("");
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
        txt6.setText("");
        
       
        
    }
void Limpiar2(){
        txtu.setText("");
        txte.setText("");
        txta.setText("");
        txtev.setText("");
        txtcr.setText("");
        
       
        
    }

void Limpiar4(){
        cate.setText("");
        w.setText("");
        e.setText("");
        r.setText("");
        clb.setText("");
        y.setText("");
        u.setText("");
        i.setText("");
        o.setText("");
        p.setText("");
        l.setText("");
        k.setText("");
        
       
        //confirmar.setText("");
       
        
    }
void MostrarTabla(){
        new Negocio.PuenteCalifas().PuenteMostrarTabla(TablaDatos);
        
    }
    void MostrarTablax1(){
        new Negocio.PuenteRegistro().PuenteMostrarTablax1(TablaDatosx1);
        
    }
    void MostrarTabla2(){
        new Negocio.PuenteEvaluacion().PuenteMostrarTabla2(TablaDatos2);
        
    }
    void MostrarTabla3(){
        new Negocio.PuenteLista().PuenteMostrarTabla3(TablaDatos3);
        
    }
    void MostrarTabla4(){
        new Negocio.PuentePlaneacion().PuenteMostrarTabla4(TablaDatos4);
        
    }void Limpiarx1(){
        clb.setText("");
        r.setText("");
        y.setText("");
        u.setText("");
        i.setText("");
        o.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Revisión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Revisión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Revisión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Revisión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Revisión().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelPestañas;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JTable TablaDatos2;
    private javax.swing.JTable TablaDatos3;
    private javax.swing.JTable TablaDatos4;
    private javax.swing.JTable TablaDatosx1;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField buscar1;
    private javax.swing.JTextField cate;
    private javax.swing.JTextField clb;
    private javax.swing.JTextField e;
    private javax.swing.JTextField i;
    private javax.swing.JTextField idx;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea k;
    private javax.swing.JTextArea l;
    private javax.swing.JLabel lbMostrarImagen;
    private javax.swing.JLabel lbMostrarImagen2;
    private javax.swing.JTextField mnmc;
    private javax.swing.JTextField mz;
    private javax.swing.JTextField o;
    private javax.swing.JTextField oloc;
    private javax.swing.JTextField olon;
    private javax.swing.JTextField olonc;
    private javax.swing.JTextArea p;
    private javax.swing.JPanel pEscolares;
    private javax.swing.JPanel pResumen;
    private javax.swing.JTextField r;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JPanel txtNombre;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtcr;
    private javax.swing.JTextField txte;
    private javax.swing.JTextField txtev;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtnc;
    private javax.swing.JTextField txtu;
    private javax.swing.JComboBox<String> txtx;
    private javax.swing.JTextField u;
    private javax.swing.JTextField w;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
